baseURL = "https://janikvonrotz.ch/"
languageCode = "en-us"
title = "ğ™¹ğšŠğš—ğš’ğš” ğšŸğš˜ğš— ğšğš˜ğšğš£"
description = "Curious, Dedicated, Open-Minded" 
theme = "hugo-new-css-theme"
pygmentsCodeFences = "true"
# googleAnalytics = "UA-31105856-2"
# disqusShortname = "janikvonrotz-1"

[markup.goldmark.renderer]
    unsafe = true

[permalinks]
    post = "/:year/:month/:day/:slug/"
    page = "/:slug/"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Projects"
        url = "/projects/"
        weight = 2

    [[menu.main]]
        name = "Downloads"
        url = "/downloads/"
        weight = 3

    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 4

    [[menu.main]]
        name = "CV"
        url = "/cv/"
        weight = 5

    [[menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 6

[params]
    description = "Curious, Dedicated, Humble"
    subscribeURL = "https://eepurl.com/geDd05"
    plausibleAnalaytics = "janikvonrotz.ch"
    gitUrl = "https://github.com/janikvonrotz/janikvonrotz.ch/tree/master/content"
    
    [params.remark42]
    url = "https://comment.janikvonrotz.ch"
    siteId = "janikvonrotz.ch"

    [params.logo]
    url = "/images/logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "/images/logo.png"

    [params.archive]
    url = "/archive/"

    [params.search]
    url = "/search/"
    img = "/images/search.svg"

[outputs]
    section = ["JSON", "HTML"]
