baseurl = "https://example.org"
languageCode = "en-us"
title = "Lithium Theme"
theme = "hugo-lithium-theme"
themesDir = "../../"
googleAnalytics = ""
disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = ""
[[menu.main]]
    name = "Twitter"
    url = ""

[params]
    description = ""
    subscribeURL = ""

    [params.logo]
    url = "/images/logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"

    [params.archive]
    url = "/archive/"
    
    [params.search]
    url = "/search/"
    img = "/images/search.svg"

[outputs]
    section = ["JSON", "HTML"]