name = "Lithium"
license = "MIT"
licenselink = "https://github.com/janikvonrotz/hugo-lithium-theme/blob/master/LICENSE.md"
description = "Lithium minimal theme"
homepage = "https://github.com/janikvonrotz/hugo-lithium-theme"
tags = ["blog"]
features = ["blog", "google analytics", "responsive", "disqus", "twitter cards", "dark mode"]
min_version = 0.15

[author]
  name = "Janik von Rotz"
  homepage = "https://janikvonrotz.ch/"